### ISSUE TITLE
Move colour processing to walker.js

### ISSUE THREAD

**Issue by CCruzG** [GenArtRepo/dla#1]
```
                    //TODO move colour processing to walker.js (keep track of distance travelled) @crarojasca
```
The colour processing can be done within the walker.js class by keeping track of distance travelled.

https://github.com/GenArtRepo/dla/blob/b68cf723aac0897f19fe2ec1445c6e40b0924da3/sketch.js#L88-L96

**Comment by crarojasca** [comment]
Yeap you're right. Done.
