### ISSUE TITLE
Eliminate 'n' setting (or make the sketch work in a different way).

### ISSUE THREAD

**Issue by CCruzG** [GenArtRepo/dla#2]
```
      //TODO 
```

The 'n' setting does not work, as all the walkers are created in the init() function, which is called in setup. 

Two alternatives:
- Eliminate 'n' from settings.
- Start the live version of the sketch in pause mode and use 'n' to determine number of walkers before execution.

https://github.com/GenArtRepo/dla/blob/b68cf723aac0897f19fe2ec1445c6e40b0924da3/sketch.js#L41

**Comment by crarojasca** [comment]
@CCruzG I was wondering about a good way to increase or decrease the number of walkers dynamically as we did in flocking, and actually, I can remove them but at the moment of adding new ones, they could appear in the zones already frozen. I tried generating them in the center in a random direction but I conclude creating an enormous freeze donut as well. A good way would be by letting the user click the empty places to create new walkers I guess, but for the moment I start the live version paused as you suggested in the second option.
